### ISSUE TITLE
Add categorization tags for this repository

### ISSUE THREAD

**Issue by arbox** [secryst/secryst#31]
As a maintainer of the Ruby NLP list (https://github.com/arbox/nlp-with-ruby) I'd kindly as you to consider adding some of tags to this repository like `rubynlp`, `rubyml`, `ruby`.

Tags are a great way to do networking with relevant projects and enhance greatly searchability on GitHub.

Thank you!

**Comment by ronaldtse** [comment]
Thank you @arbox for the great suggestion and for the listing. We've just added the tags!
