### ISSUE TITLE
“Test model” failure on Ruby 2.6 on macOS and Ubuntu

### ISSUE THREAD

**Issue by ronaldtse** [secryst/secryst#39]
All tests now pass but “Test model” fails on Ruby 2.6.

We should also separate the tests into different GHA workflows so that the Python tests, libtorch training tests are run separately, they don’t depend on each other. 

_Originally posted by @ronaldtse in https://github.com/secryst/secryst/issues/34#issuecomment-846338351_

**Comment by mib32** [comment]
@ronaldtse 👍

**Comment by ronaldtse** [comment]
As per our discussion, we're going to drop support for Ruby 2.6 due to model loading issues.

Done in 18ba569a29c5a25f9f3ecfc8eaf4adc7776a59f4.
